
export const DASHBOARD_DETAILS = 'DASHBOARD_DETAILS';
export const THING_DETAILS = 'THING_DETAILS';
export const USER_DETAILS = 'USER_DETAILS';
export const GROUPWISE_THINGLIST = 'GROUPWISE_THINGLIST';