import {StyleSheet} from 'react-native';
import {WHITE} from '../../constants/color';
import {WIDTH} from '../../constants/config';

export const DeviceStyles = StyleSheet.create({
  container: {
    width: '95%',
    alignSelf: 'center',
    marginBottom: 10,
  },
  boxcontainer: {
    borderRadius: 15,

    width: '100%',
    alignSelf: 'center',
    marginBottom: '15%',
    marginTop: '10%',
    elevation: 3,
    backgroundColor: WHITE,
  },
  box: {
    borderRadius: 10,
    backgroundColor: '#fff',
    height: '130%',
    width: '100%',
    alignSelf: 'center',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 3,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    margin: 10,
  },
  headerLeft: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: 50,
  },
  icon: {
    height: 50,
    width: 50,
  },
  headerText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 15,
    marginLeft: 5,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 5,
  },
  statusIcon: {
    height: 20,
    width: 28,
    marginTop: 4,
    marginLeft: 15,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    margin: 8,
  },
  infoBox: {
    borderRadius: 10,
    width: '40%',
    height: 30,
    backgroundColor: '#f4fdf4',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  infoIcon: {
    height: 20,
    width: 20,
    marginTop: 4,
  },
  infoText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
    paddingTop: 4,
  },
  innerContainer: {
    borderRadius: 10,
    backgroundColor: '#fff',
    height: '130%',
    width: '100%',
    alignSelf: 'center',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 3,
    display: 'flex',
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    margin: 10,
  },
  headerContent: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: 50,
  },
  headerImage: {
    height: 50,
    width: 50,
  },
  headerText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 15,
    marginLeft: 5,
  },
  modeContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 5,
  },
  modeImage: {
    height: 20,
    width: 28,
    marginTop: 4,
    marginLeft: 15,
  },
  detailsContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    margin: 8,
  },
  detailBox: {
    borderRadius: 10,
    width: '40%',
    height: 30,
    backgroundColor: '#f4fdf4',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  detailImage: {
    height: 20,
    width: 20,
    marginTop: 4,
  },
  detailText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
    paddingTop: 4,
  },
  headerText: {
    marginBottom: 10,
    fontWeight: '600',
    fontSize: 17,
    color: '#000',
  },
  fanList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  fanCard: {
    width: '30%',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 15,
    elevation: 5,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  fanHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 10,
  },
  fanTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#333',
  },
  fanStatus: {
    fontSize: 15,
    fontWeight: '400',
    color: '#666',
  },
  fanImage: {
    height: 60,
    width: 60,
  },
  sectionContainer: {
    borderRadius: 10,
    backgroundColor: '#fff',
    padding: 10,
    marginBottom: 10,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
  },
  sectionContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 30,
  },
  sectionImage: {
    height: 50,
    width: 50,
  },
  sectionText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: 4,
  },
  statusContainer: {
    borderRadius: 10,
    backgroundColor: '#f4fdf4',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 5,
    marginBottom: 10,
    width: WIDTH * 0.41,
  },
  statusImage: {
    height: 20,
    width: 20,
    marginRight: 5,
  },
  statusText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'black',
  },
  rowView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});
//  ellipsizeMode={'tail'}
//                   numberOfLines={1}
