import {StyleSheet} from 'react-native';
import {HEIGHT, WIDTH} from '../../constants/config';
import {BLACK} from '../../constants/color';

export const Thingsstyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
  },
  card: {
    borderRadius: 10,
    backgroundColor: '#fff',
    height: HEIGHT * 0.23,
    width: '90%',
    margin: 15,
    alignSelf: 'center',
    shadowColor: '#000000',
    padding: 5,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 3,
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  leftSection: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: '60%',
    height: '100%',
  },
  image: {
    height: 80,
    width: 60,
  },
  avgTempLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
  },
  avgTempValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
  },
  reqTempContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    borderRadius: 10,
    backgroundColor: 'green',
    marginTop: 7,
    paddingVertical: 4,
    alignItems: 'center',
  },
  reqTempLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  outsideTempLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
  },
  rightSection: {
    width: '40%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  tempColumn: {
    flexDirection: 'column',
    borderRightWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderStyle: 'dashed',
    marginTop: 10,
  },
  tempLabel: {
    fontSize: 8,
    fontWeight: 'bold',
    color: 'black',
    padding: 3,
  },
  tempValue: {
    borderBottomWidth: 1,
    padding: 7,
    borderStyle: 'dashed',
    color: BLACK,
  },
  humidityContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    height: '18%',
    backgroundColor: 'white',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 3,
    borderRadius: 15,
    width: '81%',
  },
  humidityLeftSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  humidityImage: {
    height: 80,
    width: 70,
    marginLeft: 10,
  },
  humidityTextContainer: {
    marginLeft: 20,
  },
  humidityLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
  },
  humidityValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
  },
  humidityRightSection: {
    alignItems: 'flex-end',
  },
  reqHumidityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'skyblue',
    width: '100%',
    marginRight: 10,
    padding: 5,
  },
  reqHumidityLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
    marginRight: 35,
  },
  reqHumidityValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
    textAlign: 'left',
  },
  containerco2: {
    height: HEIGHT * 0.18,
    width: '90%',
    marginBottom: 10,
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    width: '95%',
    marginTop: 10,
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'space-evenly',
  },
  cardco2: {
    borderRadius: 15,
    backgroundColor: 'white',
    width: '45%',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 3,
    // marginHorizontal: 5,
    alignSelf: 'center',
  },
  cardContent: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    padding: 10,
  },
  image: {
    height: HEIGHT * 0.1,
    width: WIDTH * 0.1,
  },
  textContainer: {
    marginLeft: 10,
  },
  title: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 10,
  },
  value: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
  },
  ventContainer: {
    borderRadius: 10,
    backgroundColor: 'white',
    height: HEIGHT * 0.15,
    marginBottom: 10,
    width: WIDTH * 0.9,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 3,
  },
  ventContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
    padding: 10,
    borderBottomWidth: 0.3,
    borderColor: 'grey',
  },
  ventText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
  },
  ventImage: {
    height: 60,
    width: 60,
    marginLeft: '10%',
  },
  tableBody: {
    borderRadius: 5,
  },
  headerRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.2,
    borderBottomColor: 'gray',
    backgroundColor: 'green',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  headerItem: {
    paddingVertical: 15,
    alignItems: 'center',
    borderRightWidth: 0.5,
    borderColor: '#fff',
  },
  headerText: {
    fontWeight: '700',
    fontSize: 12,
    color: '#fff',
    textAlign: 'center',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  oddRow: {
    backgroundColor: '#f4fdf4',
  },
  evenRow: {
    backgroundColor: '#fff',
  },
  imageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  image: {
    height: 28,
    width: 25,
    marginLeft: 10,
    marginRight: 7,
  },
  imageText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: 8,
  },
  buttonImage: {
    height: 30,
    width: 30,
  },
  buttonText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: 8,
  },
  descriptionContainer: {
    marginTop: '21%',
  },
});
