export var products = [
  {
    pid: '2',
    pname: 'Mobile Phones',
    vendor: 'Company',
    mrp: '3000',
    batchno: '1',
    batchdate: new Date(),
    quantity: '3',
    status: 'approved',
    editrequest: false,
  },
  {
    pid: '3',
    pname: 'Laptop',
    vendor: 'Tech Co',
    mrp: '1500',
    batchno: '2',
    batchdate: new Date(),
    quantity: '5',
    status: 'approved',
    editrequest: false,
  },
  {
    pid: '4',
    pname: 'Television',
    vendor: 'Electronics Inc',
    mrp: '2500',
    batchno: '3',
    batchdate: new Date(),
    quantity: '2',
    status: 'approved',
    editrequest: false,
  },
  {
    pid: '5',
    pname: 'Headphones',
    vendor: 'AudioTech',
    mrp: '500',
    batchno: '4',
    batchdate: new Date(),
    quantity: '10',
    status: 'approved',
    editrequest: false,
  },
  {
    pid: '1',
    pname: 'Electric Fan',
    vendor: 'Company',
    mrp: '1200',
    batchno: '1',
    batchdate: new Date(),
    quantity: '3',
    status: 'approved',
    editrequest: false,
  },
];
